version: "3.8"

services:
  processing:
    platform: linux/amd64
    build:
      context: ../..
      dockerfile: ./scripts/memtest/Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    restart: "no"
    volumes:
      - ./scripts/memtest:/memtest
      - ./cellxgene_schema_cli:/cellxgene_schema_cli
      - ./data:/data
