fixup_gene_symbols:
  X: log1p
  raw.X: raw
obs:
  assay_ontology_term_id: EFO:0008930
  ethnicity_ontology_term_id: na
  sex:
    sex:
      M: male
      F: female
  disease_ontology_term_id: PATO:0000461
  development_stage_ontology_term_id: EFO:0001272
  cell_type_ontology_term_id:
    BICCN_subclass_label:
      L6 IT: CL:0000679
      Sst: CL:0000617
      VLMC: CL:0000708
      L5 IT: CL:0000679
      L4: CL:0000679
      Lamp5: CL:0000617
      Sncg: CL:0000617
      Vip: CL:0000617
      Astro: CL:0000127
      Pvalb: CL:0000617
      L6 CT: CL:0000679
      No Class: unknown
      NP: CL:0000679
      L2/3 IT: CL:0000679
      L5 PT: CL:0000679
      L6b: CL:0000679
      Oligo: CL:0000128
      Serpinf1: CL:0000617
      Endo: CL:0000115
      SMC: CL:0000192
      Meis2: CL:0000617
      CR: CL:0000679
      Macrophage: CL:0000235
      Peri: CL:0000669
  tissue_ontology_term_id:
    brain_region:
      VISp: UBERON:0002436
      ALM: UBERON:0001870
uns:
  version:
    corpora_schema_version: 1.1.0
    corpora_encoding_version: 0.1.0
  organism: Mus musculus
  organism_ontology_term_id: NCBITaxon:10090
  layer_descriptions:
    X: log(CPM+1)
    raw.X: raw
  publication_doi: https://doi.org/10.1038/nn.4216
  title: Shared and distinct transcriptomic cell types across neocortical areas

