obs:
  assay_ontology_term_id: 10X
  ethnicity_ontology_term_id: unknown
  sex:
    sex:
      M: MALE
      F: FEMALE
  disease_ontology_term_id: PATO:0000461
  tissue_ontology_term_id: UBERON:0001384
  cell_type_ontology_term_id:
    sub_cluster_name:
      GABAergicLamp5: CL:0000617
      GABAergicProg/IP: CL:0000617
      GABAergicPvalb: CL:0000617
      GABAergicSncg: CL:0000617
      GABAergicSst: CL:0000617
      GABAergicVip: CL:0000617
      GlutamatergicCR: CL:0000679
      GlutamatergicL2/3 IT: CL:0000679
      GlutamatergicL5 ET: CL:0000679
      GlutamatergicL5 IT: CL:0000679
      GlutamatergicL5/6 NP: CL:0000679
      GlutamatergicL6 CT: CL:0000679
      GlutamatergicL6 IT: CL:0000679
      GlutamatergicL6 IT Car3: CL:0000679
      GlutamatergicL6b: CL:0000679
      Non-NeuronalAstro: CL:0000127
      Non-NeuronalEndo: CL:0000115
      Non-NeuronalMacrophage: CL:0000235
      Non-NeuronalMicro: CL:0000129
      Non-NeuronalOPC: CL:0002453
      Non-NeuronalOligo: CL:0000128
      Non-NeuronalPeri: CL:0000669
      Non-NeuronalProg/IP: prog
      Non-NeuronalSMC: CL:0000192
      Non-NeuronalVLMC: CL:0000708
uns:
  version:
    corpora_schema_version: 1.1.0
    corpora_encoding_version: 0.1.0
  organism: Mus musculus
  organism_ontology_term_id: ' NCBITaxon:10090'
  layer_descriptions:
    X: log1p
  publication_doi: https://doi.org/10.1101/2020.02.29.970558
  title: 'An integrated transcriptomic and epigenomic atlas of mouse primary motor
    cortex cell types: 10xA'

