from cellxgene_ontology_guide.ontology_parser import OntologyParser

ONTOLOGY_PARSER = OntologyParser(schema_version="v5.3.0")
ASSAY_VISIUM = "EFO:0010961"
ASSAY_VISIUM_11M = "EFO:0022860"
ASSAY_SLIDE_SEQV2 = "EFO:0030062"
VISIUM_AND_IS_SINGLE_TRUE_MATRIX_SIZE = 4992
VISIUM_11MM_AND_IS_SINGLE_TRUE_MATRIX_SIZE = 14336
VISIUM_TISSUE_POSITION_MAX_ROW = 77
VISIUM_TISSUE_POSITION_MAX_COL = 127
VISIUM_11MM_TISSUE_POSITION_MAX_ROW = 127
VISIUM_11MM_TISSUE_POSITION_MAX_COL = 223
SPATIAL_HIRES_IMAGE_MAX_DIMENSION_SIZE = 2000
SPATIAL_HIRES_IMAGE_MAX_DIMENSION_SIZE_VISIUM_11MM = 4000
CONDITION_IS_VISIUM = "a descendant of 'EFO:0010961' (Visium Spatial Gene Expression)"
CONDITION_IS_VISIUM_11M = f"'{ASSAY_VISIUM_11M} (Visium CytAssist Spatial Gene Expression, 11mm)"
CONDITION_IS_SEQV2 = f"'{ASSAY_SLIDE_SEQV2}' (Slide-seqV2)"
ERROR_SUFFIX_SPATIAL = f"obs['assay_ontology_term_id'] is either {CONDITION_IS_VISIUM} or {CONDITION_IS_SEQV2}"
ERROR_SUFFIX_VISIUM = f"obs['assay_ontology_term_id'] is {CONDITION_IS_VISIUM}"
ERROR_SUFFIX_VISIUM_11M = f"obs['assay_ontology_term_id'] is {CONDITION_IS_VISIUM_11M}"
ERROR_SUFFIX_IS_SINGLE = "uns['spatial']['is_single'] is True"
ERROR_SUFFIX_VISIUM_AND_IS_SINGLE_TRUE = f"{ERROR_SUFFIX_VISIUM} and {ERROR_SUFFIX_IS_SINGLE}"
ERROR_SUFFIX_VISIUM_AND_IS_SINGLE_TRUE_FORBIDDEN = f"is only allowed for {ERROR_SUFFIX_VISIUM_AND_IS_SINGLE_TRUE}"
ERROR_SUFFIX_VISIUM_AND_IS_SINGLE_TRUE_REQUIRED = f"is required for {ERROR_SUFFIX_VISIUM_AND_IS_SINGLE_TRUE}"
ERROR_SUFFIX_VISIUM_AND_IS_SINGLE_TRUE_IN_TISSUE_0 = f"{ERROR_SUFFIX_VISIUM_AND_IS_SINGLE_TRUE} and in_tissue is 0"
GENE_CHECKERS = {}
