name: Updates to GENCODE Files

on:
  push:
    paths:
      - '**/cellxgene_schema_cli/cellxgene_schema/gencode_files/gene_info.yml'
    branches-ignore:
      - main

jobs:
  ontology-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: "3.10"
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: install requirements
        run: |
          pip install -r cellxgene_schema_cli/requirements.txt
      - name: setup git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: gene-processing
        run: |
          make gene-processing -C cellxgene_schema_cli
          git add ./cellxgene_schema_cli/cellxgene_schema/ontology_files/genes_*.csv.gz
          git add ./cellxgene_schema_cli/cellxgene_schema/ontology_files/*_diff.txt
      - name: Commit
        run: |
          git commit -m "AUTO: update gencode files"
          git push

  unit-tests:
    runs-on: ubuntu-latest
    needs: ontology-processing
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Python cache
        uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: |
          pip install -r cellxgene_schema_cli/requirements.txt
          pip install -r requirements-dev.txt
      - name: Unit tests
        run: make unit-test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
